pluginsGLPI/tag

inc/tag.class.php
=> add printercounters blacklist fix #35

inc/tag.class.php
I added `ITILSolution` to itemtypes that should not support tagging feature.
=> Fix solution form; fixes #55

js/entity.js
It seems to also fix the duplication of the "is_recursive" select element.
=> Fix double display of entities tags

front/tag.form.php, inc/tag.class.php, inc/tagitem.class.php, plugin.xml, setup.php
- Use array conditions instead of string in CommonDBTM::find()
- Replace usage of deprecated KnowbaseItem::addVisibilityJoins()
=> GLPI 9.4 compatibility

hook.php
=> fix: AllAssets itemtype

inc/tag.class.php
=> fix: tag dropdown query

inc/tag.class.php
Better code to retrieve itemtype when plugin try try to register itself for hooks
See https://github.com/pluginsGLPI/tag/issues/82
Best regards
=> fix(core): refactor code to get itemtype

setup.php
Signed-off-by: Stanislas <skita@teclib.com>
Add fusion inventory task to list of itemtype
=> Add fusion inventory task

hook.php
Fixes #103 
Fixes #84 
Tested multiple search queries to ensure it was fixed.
=> Fix searching for multiple tags

hook.php, inc/config.class.php, inc/tag.class.php, setup.php
Add tag block location config option which defaults to existing behavior (Show on top).
Deprecated preItemForm function in favor of a more generic showForItem function.
Closes #65
=> Allow changing tag display location

inc/tag.class.php
Fix method to get current itemtype 
Actually this methode take carre only plugin path 
but we have new location for plugins -> marketplace
this PR fix it.
Best regrds
=> fix(core): fix regex to match marketplace or plugins folder

inc/tag.class.php, js/kanban.js, setup.php
Built on `feature/glpi-10.0`.
Relies on glpi-project/glpi#10214
Adds the following filters to Kanbans:
- tagged: True or false if an item has tags
- tag: Filters items with a specific tag
=> Add Kanban filtering integration

hook.php, setup.php
=> Wait all plugins are loaded for update hooks

css/tag.css, js/kanban.js
Add ability to click the tags in the Kanban items to automatically apply that tag as a filter.
=> Click to filter in Kanban

hook.php, inc/tagitem.class.php, setup.php
Allows you to add a tag via business rules for tickets
=> feat: add tag by ticket rule

inc/tag.class.php
=> Fix margin on tasks

setup.php
Support adding tags on webhooks
glpi-project/glpi#14916
Ref: !26398
=> Support webhooks

.github/workflows/locales-sync.yml, .github/workflows/locales-update-source.yml
=> Add workflows to sync locales

inc/tag.class.php, templates/forms/tag.html.twig
- It fixes !34051
- Add `is_active` field to enable/disable a tag
=> Feat: Enable/disable a tag

front/tag.php
Add missing Session::checkLoginUser();
=> Fix: front/ check

plugin.xml, tests/bootstrap.php
- It fixes # (issue number, if applicable)
=> GLPI 11 compat: XML for beta

hook.php, inc/tagitem.class.php, tests/TagTestCase.php, tests/units/TagItemTest.php, tests/units/TagRuleTest.php
partial revert / adapt of https://github.com/pluginsGLPI/tag/pull/232
Keep `'item_update'` for rules but add `pre_item_purge` (like before)
=> Fix(Tag): fix invoked hook

CHANGELOG.md, inc/config.class.php, inc/profile.class.php
=> Fix(core): fix menu icon

CHANGELOG.md, setup.php
Replace  https://github.com/pluginsGLPI/tag/pull/248
=> Feat(Core): ExternalEvent compatibility

.twig_cs.dist.php, ajax/get_entity_tags.php, ajax/tag.php, front/tag.form.php, hook.php, inc/config.class.php, inc/profile.class.php, inc/tag.class.php, inc/tagitem.class.php, psalm.xml, rector.php, setup.php, tests/Units/TagRuleTest.php
=> Feat(CI): add psalm + rector

CHANGELOG.md, inc/tag.class.php
use `Asset_PeripheralAsset` instead of `Computer_Item`
=> Fix(Core): use Asset_PeripheralAsset instead of Computer_Item
