pluginsGLPI/tag

- setup.php
Signed-off-by: Stanislas <skita@teclib.com>
This warning is display when uninstall plugin is installed and activated,
```
PHP Warning(2): Invalid argument supplied for foreach()
Backtrace :
plugins/tag/setup.php:90
inc/plugin.class.php:168 plugin_init_tag()
inc/includes.php:104 Plugin::load()
front/cron.php:38 include()
```
because uninstall is load after tag, and global variable is not initialize.
to prevent this, uninstall is load if it installed and activated.
see #81 and #77
> fix(core): load plugin if needed

- hook.php
Signed-off-by: Stanislas <skita@teclib.com>
Use 'dropdown' datatype rather than 'string'
Use 'equals, notequals, contains' searchtype rather than 'contains'
Best regards
> Refactor tickets search engine

- setup.php
Make the following itemtypes taggable:
- Enclosure
- PDU
- PassiveDCEquipment
- Certificate
- Appliance
- Cluster
- Domain
- ProjectTask (Needed for Kanban)
> Add some taggable itemtypes

- inc/tag.class.php
- inc/tagitem.class.php
When ITIL Object manage sub itemetyp like Project -> Ticket / Project -> Computer
tag display option to add or remove tag but not tag are displayed because itemtype is 'Itil_Project' or 'Item_Project' which are not understand by plugin.
Thoose class used to create lionk between project and other itemtype.
On TagItem class remove 'update' action form massive action see https://github.com/pluginsGLPI/tag/issues/78
this PR prenvet this
> Remove usless massive action on subitem

- hook.php
- inc/tag.class.php
TAG massive action (add) is display from ```FormCreatorIssue```
But dropdown is empty because connected user do not have right to update / create  ```FormCreatorIssue```
This pr resolve this
Internal ref : !23503
> fix(core): exclude PluginFormcreatorIssue itemetype

- inc/tag.class.php
Fix escaping of class name in search of items. It can happen that you can have tags defined for "TicketRecurrent" and they will be shown also for the "Ticket".
Escape with double quotes. Question is whether it can happen it will be stored in DB also without "" (so not the JSON).
At least I can see in DB it is stored also for single type tags like ["Ticket"] so fix is working for me.
> Fix Tags on items with similar class names

- js/kanban.js
In some cases, there may not be any tag data on Kanban cards and this was disrupting the creation of filters.
> fix undefined tags in kanban

- hook.php
If we search via `is_equals` the result returns too many values.
For example, if we searched for the tag with ID = 1, the result would return all tags containing 1 in the ID, so 1, 10, 11...
Before:
After:
> fix: search by tag

- inc/tagitem.class.php
When a user does not have the right to update tags, if he modifies a ticket with tags already linked, they disappear when the ticket is saved.
ref !27746
> fix: update right

- inc/tag.class.php
Fix error message when `itemtype = ''`
```
glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "" not found in /var/www/html/glpi/marketplace/tag/hook.php at line 73
Backtrace :
src/Plugin.php:1852                                plugin_tag_getAddSearchOptionsNew()
src/Search.php:7992                                Plugin::getAddSearchOptionsNew()
src/Search.php:7679                                Search::getOptions()
src/SavedSearch.php:590                            Search::getCleanedOptions()
src/SavedSearch.php:1238                           SavedSearch->prepareQueryToUse()
src/SavedSearch.php:830                            SavedSearch->execute()
src/SavedSearch.php:869                            SavedSearch->getMine()
ajax/savedsearch.php:87 …
```
> fix: empty itemtype

- inc/tag.class.php
Itemtypes were moved to a CFG_GLPI array 5 years ago and the `getItemtypes` method was removed.
This affected searching tags by itemtype and affected migrating from a very old plugin version where the `type_menu` fields were changed from being a menu name to a list of specific itemtypes.
> fix refs to removed getItemtypes

- setup.php
Webhook class doesn't exist in 10.0 (or 10.1 currently) so an error is thrown on the tag form. This PR only adds it to the itemtype array if the class exists.
> Fix missing Webhook class

- hook.php
- inc/tagitem.class.php
Tag may be added through the "Add tags" rule action, however this wont work for ticket coming from GLPI's mail receivers due to the way the plugin declare its hooks.
Fixed by forcing the hook on ticket to always be active.
> Fix broken tag rules with ticket created from mails

- inc/tagitem.class.php
Fix !30667
Tag may be added by automatic actions (mailgate -> ticket creation -> ticket rule -> add tag action), in this case we must not check the session rights as there is no real user logged in.
> Fix tag from cron

- inc/tag.class.php
- It fixes #206 
Fix this error message:
`SQL Error "1054": Unknown column 'is_active' in 'where clause' in query "SELECT * FROM glpi_plugin_tag_tags WHERE is_active = '1' AND ((type_menu IS NULL) OR (type_menu = '') OR (type_menu = '0') OR (type_menu LIKE '%"PluginMfaConfig"%')) ORDER BY name"`
> fix: Unknown column 'is_active'

- inc/tag.class.php
- [X ] I have performed a self-review of my code.
- [X ] I have added tests (when available) that prove my fix is effective or that my feature works.
By design you will see Tag dropdown on all objects, but in fact you nee to display the dropdown only on itemtypes with active tag
> See Tag Only On Active Itemtypes

- .gitignore
- CHANGELOG.md
- composer.json
- composer.lock
- hook.php
- inc/tagitem.class.php
- phpunit.xml
- tests/TagTestCase.php
- tests/bootstrap.php
- tests/units/TagRuleTest.php
- It fixes !35539
Adding a tag using the rules engine is impossible when triggered with a self-service profile. This PR identifies tag addition by the rule engine and ignores the tag addition right of the triggering profile.
> Fix assign tags from rules

- inc/tag.class.php
- inc/tagitem.class.php
- It fixes !35473
- This PR fixes an issue that prevents users without authoring rights on a given object type from adding tags to these objects. To add a tag, you must have the right to update the object.
> fix(massiveAction): Fixed bug preventing the addition of tags to objects without creation rights

- CHANGELOG.md
- hook.php
- inc/tagitem.class.php
- tests/units/TagRuleTest.php
- It fixes !36508
Adding multiple tags via business rules doesn't work. If, for example, two rules each adding a tag are triggered when a ticket is created, only one tag is added.
This PR therefore adds the `Add` option to the `Add tag` action in the rules.
This PR corrects the problem if this patch is present: https://github.com/glpi-project/glpi/pull/19058
> Fix the addition of multiple tags via rules

- CHANGELOG.md
- hook.php
- tests/units/TagRuleTest.php
- It fixes !36334
If we create the following rule : 
**Criteria** : _Requester in group_ | _is_ | _Group 1_
**Actions** : _Add tags_ | _Assign_ | _Test Tag_
With in `Group 1`, the user named `User2`
We create a ticket with `User1` as requester.
Update the ticket, changing only the requester to `User2`.
The rule is supposed to be played and the tag added.
However, modifying only the actors doesn't take you through the ticket update process, you're stopped at the `pre_item_update` stage, as the rest must be managed by `TicketUser` or equivalent.
As a result, the code that adds the tag is not reached and, consequently, the tag is not added as it should be.
The solution is to switch to the tag …
> Fix -  Add tag from a rule when updating actors only

- hook.php
If we search for an item that does not contain a specific tag, the "is not" search will not work. For example, if a ticket has a tag "Tag1" and "Tag2", and we perform this search:
the ticket is still returned
To work, it also needs this PR in the core: https://github.com/glpi-project/glpi/pull/18978
> Search Options: fix negative tag research
